### ISSUE TITLE
I'm stuck on the outline 

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/arrrgenes-treasure-tours#1]
Hey! So I think I remember Chelle saying something about the h2 needing a bg colour instead when markbot would say it needs more contrast? I got an error for the nav links with a error message along those lines.  
<img width="800" alt="Screen Shot 2021-04-12 at 8 51 51 AM" src="https://user-images.githubusercontent.com/77282460/114397178-62b90d00-9b6c-11eb-9425-d233f36af60c.png">

Sorry I'm A little confused on what to do?

@hellachella @raven-rhea

**Comment by raven-rhea** [comment]
I think its asking to add a focus state to your nav a's try adding this 
.nav a:focus {
  outline: .15rem solid #fff;
}

**Comment by EmmaJLussier** [comment]
Thank you I think that worked I got that h2 error I think 
<img width="802" alt="Screen Shot 2021-04-12 at 9 47 05 AM" src="https://user-images.githubusercontent.com/77282460/114404829-1245ad80-9b74-11eb-9a58-26d70895d877.png">
What was I supposed to do here?

**Comment by raven-rhea** [comment]
so try adding a background-color to your banner

**Comment by raven-rhea** [comment]
a dark background colour I should say that way if your img doesnt load for some reason you can still see the text

**Comment by EmmaJLussier** [comment]
Thanks Raven All worked out :)

**Comment by raven-rhea** [comment]
Amazing!
